version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    image: harshit2004h/real-estate-rental:server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    networks:
      - app-network
    image: harshit2004h/real-estate-rental:client

networks:
  app-network:
    driver: bridge
